In [2]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle

In [4]:
## Load the model, scaler and encoder
model = load_model('model.h5')

with open('label_encoder.pkl','rb') as file:
    label_encoder=pickle.load(file)

with open('ohe_geography.pkl','rb') as file:
    ohe_geography=pickle.load(file)

with open('StandardScaler.pkl','rb') as file:
    standardScaler=pickle.load(file)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [5]:
## Input data
input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [6]:
## OneHotEncoder expects a 2D input
geo_encoded = ohe_geography.transform([[input_data['Geography']]])
geo_encoded_df = pd.DataFrame(geo_encoded,columns=ohe_geography.get_feature_names_out(['Geography']))
geo_encoded_df

d:\Customer-churn-prediction\venv\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [ ]:
# Converting dictionary into dataframe
input_df = pd.DataFrame([input_data])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,60000,2,1,1,50000

In [ ]:
# Concatenate ohe output with input_df
input_df = pd.concat([geo_encoded_df,input_df.drop(['Geography'],axis=1)],axis=1)
input_df

,Geography_France,Geography_Germany,Geography_Spain,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,1.0,0.0,0.0,600,Male,40,3,60000,2,1,1,50000

In [13]:
# Encode Categorical features
input_df['Gender'] = label_encoder.transform(input_df['Gender'])
input_df

,Geography_France,Geography_Germany,Geography_Spain,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,1.0,0.0,0.0,600,1,40,3,60000,2,1,1,50000

In [14]:
# Scaling the input data
input_scaled = standardScaler.transform(input_df)
input_scaled

array([[ 1.00150113, -0.57946723, -0.57638802, -0.53598516,  0.91324755,
         0.10479359, -0.69539349, -0.25781119,  0.80843615,  0.64920267,
         0.97481699, -0.87683221]])

In [ ]:
## Predict the output 
output = model.predict(input_scaled)
output[0][0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step

np.float32(0.033429775)

In [22]:
if output[0][0] > 0.5:
    print("Prediction is likely to churn")
else:
    print("Prediction is not likely to churn")

Prediction is not likely to churn