In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder,OneHotEncoder
import pickle

In [3]:
data = pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
## Preprocess the data
data = data.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [5]:
## Encode Categorical features
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [6]:
## One hot encoded 'Geography'
ohe_geography = OneHotEncoder(sparse_output=False) ## sparse_output=False tells OneHotEncoder to return a dense NumPy array instead of a sparse matrix.
geo_encoder = ohe_geography.fit_transform(data[['Geography']]) ## usually returns a sparse matrix(But now returns a array bcz sparse_output=false)
geo_encoder

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]], shape=(10000, 3))

In [7]:
ohe_geography.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [8]:
geo_encoded_df = pd.DataFrame(geo_encoder,columns=ohe_geography.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [9]:
## drop column and concat with one hot encoded
data = pd.concat([geo_encoded_df,data.drop(['Geography'],axis=1)],axis=1)
data

,Geography_France,Geography_Germany,Geography_Spain,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1.0,0.0,0.0,619,0,42,2,0.00,1,1,1,101348.88,1
1,0.0,0.0,1.0,608,0,41,1,83807.86,1,0,1,112542.58,0
2,1.0,0.0,0.0,502,0,42,8,159660.80,3,1,0,113931.57,1
3,1.0,0.0,0.0,699,0,39,1,0.00,2,0,0,93826.63,0
4,0.0,0.0,1.0,850,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,1.0,0.0,0.0,771,1,39,5,0.00,2,1,0,96270.64,0
9996,1.0,0.0,0.0,516,1,35,10,57369.61,1,1,1,101699.77,0
9997,1.0,0.0,0.0,709,0,36,7,0.00,1,0,1,42085.58,1
9998,0.0,1.0,0.0,772,1,42,3,75075.31,2,1,0,92888.52,1
9999,1.0,0.0,0.0,792,0,28,4,130142.79,1,1,0,38190.78,0

In [10]:
## Divide the data into dependent and independent features
X=data.drop('EstimatedSalary',axis=1)
y=data['EstimatedSalary']

## Train test split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

## Scale the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [11]:
X_train

array([[ 1.00150113, -0.57946723, -0.57638802, ...,  0.64920267,
         0.97481699, -0.50857963],
       [-0.99850112,  1.72572313, -0.57638802, ...,  0.64920267,
         0.97481699, -0.50857963],
       [-0.99850112, -0.57946723,  1.73494238, ...,  0.64920267,
        -1.02583358,  1.96626042],
       ...,
       [ 1.00150113, -0.57946723, -0.57638802, ..., -1.54035103,
        -1.02583358,  1.96626042],
       [ 1.00150113, -0.57946723, -0.57638802, ...,  0.64920267,
        -1.02583358,  1.96626042],
       [-0.99850112,  1.72572313, -0.57638802, ...,  0.64920267,
         0.97481699, -0.50857963]], shape=(8000, 12))

## ANN Regression

In [12]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [14]:
## Build our ANN Regression model
model = Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)),
    Dense(32,activation='relu'),
    Dense(1)
])

## compile the model 
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

model.summary()

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

c:\Users\Shorya\Desktop\Customer-churn-prediction\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [17]:
## Set up TensorBoard
import datetime
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d - %H%M%S")
tensorflow_callbacks = TensorBoard(log_dir=log_dir,histogram_freq=1) ## After every epoch, save histograms of weights and biases.

In [18]:
## Set up earlyStopping
earlyStopping_callbacks = EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [19]:
## train the ANN model 
history = model.fit(
    X_train,y_train,validation_data=(X_test,y_test),epochs=100,
    callbacks=[tensorflow_callbacks,earlyStopping_callbacks]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 100390.3984 - mae: 100390.3984 - val_loss: 98563.2031 - val_mae: 98563.2031
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 99795.4141 - mae: 99795.4141 - val_loss: 97358.9297 - val_mae: 97358.9297
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 97678.8672 - mae: 97678.8672 - val_loss: 94242.9219 - val_mae: 94242.9219
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 93452.6953 - mae: 93452.6953 - val_loss: 88929.5781 - val_mae: 88929.5781
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 87094.2891 - mae: 87094.2891 - val_loss: 81782.6562 - val_mae: 81782.6562
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 79233.6875 - mae: 79233.6875 - val_loss: 73739.6250 - val_mae: 73739.6250
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 70993.7188 - mae: 70993.7188 - val_loss: 65957.2266 - val_mae: 65957.2266
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 63563.1094 - mae: 63563.1094 - val_loss: 59510.8906 - val_mae: 59510.8906
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 57782.5039 - mae: 57782.5039 - val_loss: 54984.4062 - val_mae: 54984.4062
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 53995.3242 - mae: 53995.3242 - val_loss: 52377.5859 - val_mae: 52377.5859
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 51832.4258 - mae: 51832.4258 - val_loss: 51137.6445 - val_mae: 51137.6445
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50867.7969 - mae: 50867.7969 - val_loss: 50688.9922 - val_mae: 50688.9922
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50464.1641 - mae: 50464.1641 - val_loss: 50534.0547 - val_mae: 50534.0547
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50290.9844 - mae: 50290.9844 - val_loss: 50472.0312 - val_mae: 50472.0312
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50204.9844 - mae: 50204.9844 - val_loss: 50439.7422 - val_mae: 50439.7422
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50146.1133 - mae: 50146.1133 - val_loss: 50416.6289 - val_mae: 50416.6289
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50098.9336 - mae: 50098.9336 - val_loss: 50398.6875 - val_mae: 50398.6875
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50059.9531 - mae: 50059.9531 - val_loss: 50384.0977 - val_mae: 50384.0977
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50025.0547 - mae: 50025.0547 - val_loss: 50370.8164 - val_mae: 50370.8164
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49993.3516 - mae: 49993.3516 - val_loss: 50358.9648 - val_mae: 50358.9648
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49965.6406 - mae: 49965.6406 - val_loss: 50342.7266 - val_mae: 50342.7266
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49935.7734 - mae: 49935.7734 - val_loss: 50329.2773 - val_mae: 50329.2773
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49914.1133 - mae: 49914.1133 - val_loss: 50318.4531 - val_mae: 50318.4531
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49891.0781 - mae: 49891.0781 - val_loss: 50310.3008 - val_mae: 50310.3008
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49864.9922 - mae: 49864.9922 - val_loss: 50304.3281 - val_mae: 50304.3281
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49845.8477 - mae: 49845.8477 - val_loss: 50294.7656 - val_mae: 50294.7656
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49825.5938 - mae: 49825.5938 - val_loss: 50285.1445 - val_mae: 50285.1445
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 49804.7773 - mae: 49804.7773 - val_loss: 50275.3203 - val_mae: 50275.3203
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49787.0273 - mae: 49787.0273 - val_loss: 50262.0938 - val_mae: 50262.0938
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49771.6484 - mae: 49771.6484 - val_loss: 50266.0000 - val_mae: 50266.0000
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49756.5430 - mae: 49756.5430 - val_loss: 50264.9805 - val_mae: 50264.9805
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49741.6133 - mae: 49741.6133 - val_loss: 50253.2266 - val_mae: 50253.2266
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49725.5430 - mae: 49725.5430 - val_loss: 50249.9141 - val_mae: 50249.9141
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49713.5938 - mae: 49713.5938 - val_loss: 50242.9141 - val_mae: 50242.9141
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49699.7031 - mae: 49699.7031 - val_loss: 50239.1445 - val_mae: 50239.1445
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49686.5039 - mae: 49686.5039 - val_loss: 50242.5156 - val_mae: 50242.5156
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49673.9844 - mae: 49673.9844 - val_loss: 50244.2109 - val_mae: 50244.2109
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49661.8398 - mae: 49661.8398 - val_loss: 50236.8281 - val_mae: 50236.8281
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49651.3828 - mae: 49651.3828 - val_loss: 50235.1133 - val_mae: 50235.1133
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49640.7305 - mae: 49640.7305 - val_loss: 50225.0430 - val_mae: 50225.0430
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49625.9102 - mae: 49625.9102 - val_loss: 50232.8203 - val_mae: 50232.8203
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49617.0195 - mae: 49617.0195 - val_loss: 50232.9805 - val_mae: 50232.9805
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49607.8984 - mae: 49607.8984 - val_loss: 50228.5859 - val_mae: 50228.5859
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49597.9023 - mae: 49597.9023 - val_loss: 50224.2227 - val_mae: 50224.2227
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49586.6250 - mae: 49586.6250 - val_loss: 50229.7422 - val_mae: 50229.7422
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49580.9531 - mae: 49580.9531 - val_loss: 50224.7422 - val_mae: 50224.7422
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49574.8594 - mae: 49574.8594 - val_loss: 50237.3711 - val_mae: 50237.3711
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49563.1523 - mae: 49563.1523 - val_loss: 50233.2305 - val_mae: 50233.2305
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49556.1641 - mae: 49556.1641 - val_loss: 50233.9062 - val_mae: 50233.9062
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49552.3047 - mae: 49552.3047 - val_loss: 50241.9766 - val_mae: 50241.9766
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49542.8555 - mae: 49542.8555 - val_loss: 50238.2422 - val_mae: 50238.2422
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49535.7539 - mae: 49535.7539 - val_loss: 50244.4648 - val_mae: 50244.4648
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49531.2070 - mae: 49531.2070 - val_loss: 50247.5117 - val_mae: 50247.5117
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49524.5000 - mae: 49524.5000 - val_loss: 50241.2539 - val_mae: 50241.2539

In [22]:
## load the extension
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [23]:
%tensorboard --logdir regressionlogs/fit

Reusing TensorBoard on port 6006 (pid 15896), started 0:02:34 ago. (Use '!kill 15896' to kill it.)

In [24]:
##Evaluate the model on test data
model.evaluate(X_test,y_test)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50224.2227 - mae: 50224.2227

[50224.22265625, 50224.22265625]

In [25]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.